/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EveFrmHistorial;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.Cuenta;

/**
 *
 * @author gabriel
 */
public class FrmHistorial extends javax.swing.JFrame {

    /**
     * Creates new form FrmHistorial
     */
    private FrmSatisfactorio frmcorrecto;
    private Cuenta cuenta;
    private EveFrmHistorial historial;
    public FrmHistorial(Cuenta cuenta, FrmSatisfactorio frmcorrecto, 
            EveFrmHistorial historial) {
        this.frmcorrecto = frmcorrecto;
        this.cuenta = cuenta;
        this.historial = historial;
        initComponents();
        this.llenartabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBancoTitulo = new javax.swing.JLabel();
        lblMenuTitulo = new javax.swing.JLabel();
        lblBancoTitulo1 = new javax.swing.JLabel();
        lblMenuTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDB = new javax.swing.JTable();
        btnAceptar1 = new javax.swing.JButton();

        lblBancoTitulo.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblBancoTitulo.setText("Banco de la Republica");

        lblMenuTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuTitulo.setText("Menu de Seleccion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBancoTitulo1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblBancoTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBancoTitulo1.setText("Banco de la Republica");

        lblMenuTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuTitulo1.setText("Historial de Transacciones y Consignaciones\n");

        TableDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableDB);

        btnAceptar1.setText("Aceptar");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMenuTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBancoTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                    .addComponent(btnAceptar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBancoTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenuTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        dispose();
        this.frmcorrecto.setVisible(true);
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    private void llenartabla()
    {
        ResultSet res = historial.obtenerHistorial(this.cuenta.getId());
        // Creamos las columnas.
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("tipo");
        modelo.addColumn("codigo");
        modelo.addColumn("fecha_inscripcion");
        modelo.addColumn("montototal");
        modelo.addColumn("clave");
        modelo.addColumn("ced");
        
        try
        {
            // Bucle para cada resultado en la consulta
            while (res.next())
            {
               // Se crea un array que será una de las filas de la tabla.
               Object [] fila = new Object[7]; // Hay tres columnas en la tabla

               // Se rellena cada posición del array con una de las columnas de la tabla en base de datos.
               for (int i=0;i<7;i++)
                  if (i != 5)
                  {
                      fila[i] = res.getObject(i+1);// El primer indice en rs es el 1, no el cero, por eso se suma 1.
                  }
               
               // Se añade al modelo la fila completa.
               modelo.addRow(fila);
            }
        }
        catch(SQLException ex)
        {
            System.out.println(ex);
        }
        this.TableDB.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDB;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBancoTitulo;
    private javax.swing.JLabel lblBancoTitulo1;
    private javax.swing.JLabel lblMenuTitulo;
    private javax.swing.JLabel lblMenuTitulo1;
    // End of variables declaration//GEN-END:variables
}
