/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EveFrmClave;
/**
 *
 * @author gabriel
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    private FrmError frmerror;
    private EveFrmClave errorclave;
    public FrmMenu(FrmError frmerror, EveFrmClave errorclave) {
        initComponents();
        this.frmerror = frmerror;
        this.errorclave = errorclave;
    }

    public FrmMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBancoTitulo = new javax.swing.JLabel();
        btnPagosExternos = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnConsginacion = new javax.swing.JButton();
        btnTransaccion = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBancoTitulo.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblBancoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Banco.png"))); // NOI18N
        getContentPane().add(lblBancoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 10, 1000, 70));
        lblBancoTitulo.getAccessibleContext().setAccessibleName("lblTitulo");

        btnPagosExternos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Botones/btn4.png"))); // NOI18N
        btnPagosExternos.setFocusable(false);
        btnPagosExternos.setName("btnPagos"); // NOI18N
        btnPagosExternos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosExternosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagosExternos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 310, 100));
        btnPagosExternos.getAccessibleContext().setAccessibleName("btnPagosExternos");

        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Botones/btn5.png"))); // NOI18N
        btnHistorial.setName("btnHistorial"); // NOI18N
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 310, 100));
        btnHistorial.getAccessibleContext().setAccessibleName("btnHistorial\n\n");

        btnConsginacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Botones/btn3.png"))); // NOI18N
        btnConsginacion.setFocusable(false);
        btnConsginacion.setName("btnConsignacion"); // NOI18N
        btnConsginacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsginacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsginacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 620, 90));
        btnConsginacion.getAccessibleContext().setAccessibleName("btnConsignacion");

        btnTransaccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Botones/btn1.png"))); // NOI18N
        btnTransaccion.setText("Transaccion");
        btnTransaccion.setFocusable(false);
        btnTransaccion.setName("btnTransaccion"); // NOI18N
        btnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 620, 160));
        btnTransaccion.getAccessibleContext().setAccessibleName("btnTransaccion");

        btnSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Botones/btn2.png"))); // NOI18N
        btnSaldo.setName("btnSaldo"); // NOI18N
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 270, 390));
        btnSaldo.getAccessibleContext().setAccessibleName("btnSaldoDisponible");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Menu cajero.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagosExternosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosExternosActionPerformed
        FrmClave frm = new FrmClave(5, errorclave, frmerror);
        dispose();
        // Enlazar a Transaccion
        frm.setVisible(true);
    }//GEN-LAST:event_btnPagosExternosActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        FrmClave frm = new FrmClave(4, errorclave, frmerror);
        dispose();
        // Enlazar a Transaccion
        frm.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnConsginacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsginacionActionPerformed
        FrmClave frm = new FrmClave(2, errorclave, frmerror);
        dispose();
        // Enlazar a Transaccion
        frm.setVisible(true);
    }//GEN-LAST:event_btnConsginacionActionPerformed

    private void btnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionActionPerformed
        FrmClave frm = new FrmClave(1, errorclave, frmerror);
        dispose();
        // Enlazar a Transaccion
        frm.setVisible(true);
    }//GEN-LAST:event_btnTransaccionActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        FrmClave frm = new FrmClave(3, errorclave, frmerror);
        dispose();
        // Enlazar a Transaccion
        frm.setVisible(true);
    }//GEN-LAST:event_btnSaldoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsginacion;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnPagosExternos;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBancoTitulo;
    // End of variables declaration//GEN-END:variables
}
