/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Cuenta;

/**
 *
 * @author gabriel
 */
public class FrmSaldoDisponible extends javax.swing.JFrame {

    /**
     * Creates new form FrmSaldoDisponible
     */
    private Cuenta cuenta;
    private FrmSatisfactorio frmcorrecto;
    public FrmSaldoDisponible(Cuenta cuenta, FrmSatisfactorio frmcorrecto) {
        this.cuenta = cuenta;
        this.frmcorrecto = frmcorrecto;
        initComponents();
        this.lblSaldo.setText("$"+ this.cuenta.getMonto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBancoTitulo = new javax.swing.JLabel();
        lblCorrectoTitulo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblCorrectoTitulo1 = new javax.swing.JLabel();
        lblBancoTitulo1 = new javax.swing.JLabel();
        lblCorrectoTitulo2 = new javax.swing.JLabel();
        btnAceptar1 = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();

        lblBancoTitulo.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblBancoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBancoTitulo.setText("Banco de la Republica");

        lblCorrectoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorrectoTitulo.setText("Transaccion Hecha Satisfactoriamente");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblCorrectoTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorrectoTitulo1.setText("Transaccion Hecha Satisfactoriamente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBancoTitulo1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        lblBancoTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBancoTitulo1.setText("Banco de la Republica");
        getContentPane().add(lblBancoTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 657, -1));

        lblCorrectoTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorrectoTitulo2.setText("Saldo Disponible en Cuenta");
        getContentPane().add(lblCorrectoTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 657, -1));

        btnAceptar1.setText("Aceptar");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 657, 69));

        lblSaldo.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("$");
        getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 657, 85));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        dispose();
        this.frmcorrecto.setVisible(true);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        dispose();
        this.frmcorrecto.setVisible(true);
    }//GEN-LAST:event_btnAceptar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JLabel lblBancoTitulo;
    private javax.swing.JLabel lblBancoTitulo1;
    private javax.swing.JLabel lblCorrectoTitulo;
    private javax.swing.JLabel lblCorrectoTitulo1;
    private javax.swing.JLabel lblCorrectoTitulo2;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables
}
