/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EveFrmClave;
import controller.EveTransaccion;

/**
 *
 * @author admin
 */
public class FrmTransaccion extends javax.swing.JFrame {

    /**
     * Creates new form FrmTransaccion
     */
    private EveFrmClave eveclave;
    private FrmError frmerror;
    private EveTransaccion evetransaccion;
    public FrmTransaccion(EveFrmClave eveclave, FrmError frmerror, EveTransaccion evetran) {
        initComponents();
        this.eveclave = eveclave;
        this.frmerror = frmerror;
        this.evetransaccion = evetran;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn20K = new javax.swing.JButton();
        btn50K = new javax.swing.JButton();
        btn100K = new javax.swing.JButton();
        btn200K = new javax.swing.JButton();
        btn500K = new javax.swing.JButton();
        btn1M = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn20K.setText("$20.000");
        btn20K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20KActionPerformed(evt);
            }
        });

        btn50K.setText("$50.000");
        btn50K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50KActionPerformed(evt);
            }
        });

        btn100K.setText("$100.000");
        btn100K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100KActionPerformed(evt);
            }
        });

        btn200K.setText("$200.000");
        btn200K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200KActionPerformed(evt);
            }
        });

        btn500K.setText("$500.000");
        btn500K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500KActionPerformed(evt);
            }
        });

        btn1M.setText("$1'000.000");
        btn1M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1MActionPerformed(evt);
            }
        });

        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("SELECCIONE LA CANTIDAD A RETIRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn20K)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn200K))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn50K)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn500K))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn100K)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn1M)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblMensaje)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn200K)
                    .addComponent(btn20K))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn50K)
                    .addComponent(btn500K))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn100K)
                    .addComponent(btn1M))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn20KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20KActionPerformed
        // TODO add your handling code here:
        this.gestionarConsignacion(20000);
    }//GEN-LAST:event_btn20KActionPerformed

    private void btn50KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50KActionPerformed
        // TODO add your handling code here:
        this.gestionarConsignacion(50000);
    }//GEN-LAST:event_btn50KActionPerformed

    private void btn100KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100KActionPerformed
        // TODO add your handling code here:
        this.gestionarConsignacion(100000);
    }//GEN-LAST:event_btn100KActionPerformed

    private void btn200KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200KActionPerformed
        // TODO add your handling code here:
        this.gestionarConsignacion(200000);
    }//GEN-LAST:event_btn200KActionPerformed

    private void btn500KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500KActionPerformed
        // TODO add your handling code here:
        this.gestionarConsignacion(500000);
    }//GEN-LAST:event_btn500KActionPerformed

    private void btn1MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1MActionPerformed
        // TODO add your handling code here:
        this.gestionarConsignacion(1000000);
    }//GEN-LAST:event_btn1MActionPerformed

    private void gestionarConsignacion(int valor)
    {
        if (this.evetransaccion.controlarValor(valor))
        {
            if (this.evetransaccion.enviarTransaccion(valor))
            {
                //hecho Correctamente
                this.cargarSatisfactorio();
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(this,
                "No deberias estar Aqui",
                "????",javax.swing.JOptionPane.ERROR_MESSAGE);
                System.exit(1);
            }
        }
        else
        {
            this.mostrarError();
        }
    }
    
    private void cargarSatisfactorio()
    {
        FrmSatisfactorio frm = new FrmSatisfactorio();
        this.dispose();
        frm.setVisible(true);
    }
    
    private void mostrarError()
    {
        if (this.eveclave.generarErrorHistoria())
            {
                //Cargar el Formulario de error
                this.dispose();
                this.frmerror.setVisible(true);
            }
            else
            {
                //Cerrar en el peor de los casos que la base de datos se halla cerrado
                System.exit(1);
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100K;
    private javax.swing.JButton btn1M;
    private javax.swing.JButton btn200K;
    private javax.swing.JButton btn20K;
    private javax.swing.JButton btn500K;
    private javax.swing.JButton btn50K;
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables
}
